Ejemplo 1

In [1]:
import numpy as np
from sklearn.linear_model import SGDClassifier

In [2]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([0,0,0,1])

model = SGDClassifier(max_iter=1000, tol=1e-3)
model.fit(X, Y)
results = model.predict(X)
print("Entradas:"+str(X))
print("Resultados AND:"+str(results))

Entradas:[[0 0]
 [0 1]
 [1 0]
 [1 1]]
Resultados AND:[0 0 0 1]


In [3]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([0,1,1,1])

model = SGDClassifier(max_iter=1000, tol=1e-3)
model.fit(X, Y)
results = model.predict(X)
print("Entradas:"+str(X))
print("Resultados OR:"+str(results))

Entradas:[[0 0]
 [0 1]
 [1 0]
 [1 1]]
Resultados OR:[0 1 1 1]


In [4]:
X = np.array([[0],[1]])
Y = np.array([1,0])

model = SGDClassifier(max_iter=1000, tol=1e-3)
model.fit(X, Y)
results = model.predict(X)
print("Entradas:"+str(X))
print("Resultados NOT:"+str(results))

Entradas:[[0]
 [1]]
Resultados NOT:[1 0]


In [5]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([0,1,1,0])

model = SGDClassifier(max_iter=1000, tol=1e-3)
model.fit(X, Y)
results = model.predict(X)
print("Entradas:"+str(X))
print("Resultados XOR:"+str(results))

Entradas:[[0 0]
 [0 1]
 [1 0]
 [1 1]]
Resultados XOR:[0 0 0 0]


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_stochastic_gradient.py:702: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


Ejemplo 2

In [6]:
import numpy as np

In [7]:
def calcularZ(w,x,b):
    return np.dot(w,x)+b

In [8]:
def activacion(z):
    return z

def neurona(w,x,b):
    return activacion(calcularZ(w,x,b))

In [9]:
def activacionSigmoide(z):
    return 1 / (1 + np.exp(-z))

def neuronaSigmoide(w,x,b):
    return activacionSigmoide(calcularZ(w,x,b))

In [10]:
w = [1,1,1]
x = [0.9,0.9,0.9]
b = 1

y_lineal = neurona(w,x,b)
y_sigmoide = neuronaSigmoide(w,x,b)
print("Y Lineal:"+str(y_lineal))
print("Y sigmoide:"+str(y_sigmoide))

Y Lineal:3.7
Y sigmoide:0.9758729785823308


In [11]:
w = [1,1,1]
x = [-0.9,-0.9,-0.9]
b = 1

y_lineal = neurona(w,x,b)
y_sigmoide = neuronaSigmoide(w,x,b)
print("Y Lineal:"+str(y_lineal))
print("Y sigmoide:"+str(y_sigmoide))

Y Lineal:-1.7000000000000002
Y sigmoide:0.15446526508353467


In [12]:
def activacionTanh(z):
    return np.tanh(z)

def neuronaTanh(w,x,b):
    return activacionTanh(calcularZ(w,x,b))

In [13]:
w = [1,1,1]
x = [0.9,0.9,0.9]
b = 1

y_lineal = neurona(w,x,b)
y_sigmoide = neuronaSigmoide(w,x,b)
y_tanh = neuronaTanh(w,x,b)
print("Y Lineal:"+str(y_lineal))
print("Y sigmoide:"+str(y_sigmoide))
print("Y Tangencial Hiperbólica:"+str(y_tanh))

Y Lineal:3.7
Y sigmoide:0.9758729785823308
Y Tangencial Hiperbólica:0.9987782412811311


In [14]:
w = [1,1,1]
x = [-0.9,-0.9,-0.9]
b = 1

y_lineal = neurona(w,x,b)
y_sigmoide = neuronaSigmoide(w,x,b)
y_tanh = neuronaTanh(w,x,b)
print("Y Lineal:"+str(y_lineal))
print("Y sigmoide:"+str(y_sigmoide))
print("Y Tangencial Hiperbólica:"+str(y_tanh))

Y Lineal:-1.7000000000000002
Y sigmoide:0.15446526508353467
Y Tangencial Hiperbólica:-0.9354090706030991


In [15]:
import numpy as np

In [16]:
def calcularZ(w,x,b):
    return np.dot(w,x)+b

def activacion(z):
    return 1 / (1 + np.exp(-z))

def capaNeuronal(w,x,b):
    return activacion(calcularZ(w,x,b))

In [17]:
x = np.array([[1,2,3]]) #Entradas.
print("Tamaño de matriz de entrada X (# de características) = "+str(x.shape))

w = np.array([[1,2,3],   #Pesos de Neurona 1
              [-1,-2,-3]])  #Pesos de Neurona 2
print("Tamaño de matriz de pesos W (neuronas x caracteristicas de entrada) = "+str(w.shape))

b = np.array([1,         #bias de neurona 1
              -1])        #bias de neurona 2
print("Tamaño de matriz de bias B (neuronas) = "+str(b.shape))

#w.T = W transpuesta. Rotamos la matriz para que encaje en np.dot()
y_pred = capaNeuronal(x,w.T,b)
print("Salida")
print(y_pred)
print("tamaño de salida (neuronas) = "+str(y_pred.shape))

Tamaño de matriz de entrada X (# de características) = (1, 3)
Tamaño de matriz de pesos W (neuronas x caracteristicas de entrada) = (2, 3)
Tamaño de matriz de bias B (neuronas) = (2,)
Salida
[[9.99999694e-01 3.05902227e-07]]
tamaño de salida (neuronas) = (1, 2)


Ejemplo 3

In [18]:
import numpy as np

In [19]:
def calcularZ(w,x,b):
    return np.dot(w,x)+b

def activacion(z):
    return 1 / (1 + np.exp(-z))

def capaNeuronal(w,x,b):
    return activacion(calcularZ(w,x,b))

In [20]:
x = np.array([[1,2,3]]) #Entradas.
print("Tamaño de matriz de entrada X (# de características) = "+str(x.shape))

w = np.array([[1,2,3],   #Pesos de Neurona 1
              [-1,-2,-3]])  #Pesos de Neurona 2
print("Tamaño de matriz de pesos W (neuronas x caracteristicas de entrada) = "+str(w.shape))

b = np.array([1,         #bias de neurona 1
              -1])        #bias de neurona 2
print("Tamaño de matriz de bias B (neuronas) = "+str(b.shape))

#w.T = W transpuesta. Rotamos la matriz para que encaje en np.dot()
y_pred = capaNeuronal(x,w.T,b)
print("Salida")
print(y_pred)
print("tamaño de salida (neuronas) = "+str(y_pred.shape))

Tamaño de matriz de entrada X (# de características) = (1, 3)
Tamaño de matriz de pesos W (neuronas x caracteristicas de entrada) = (2, 3)
Tamaño de matriz de bias B (neuronas) = (2,)
Salida
[[9.99999694e-01 3.05902227e-07]]
tamaño de salida (neuronas) = (1, 2)


Ejemplo 4

In [21]:
import numpy as np

def calcularZ(w,x,b):
    return np.dot(w,x)+b

def activacion(z):
    return 1 / (1 + np.exp(-z))

def capaNeuronal(w,x,b):
    return activacion(calcularZ(w,x,b))

def inicializarCapa(numCaracteristicas, numNeuronas):
    w = np.random.rand(numCaracteristicas,numNeuronas)
    w_transpose = w.T
    b = np.random.rand(numNeuronas)
    return w_transpose,b

In [22]:
#Entrada:
x = np.array([0,1,2,3,4,3,2,1,0,-1]) #10 características de entrada.
#Capa 1:
w1,b1 = inicializarCapa(10,4) #10 caracteristicas, 4 neuronas.
#Capa 2:
w2,b2 = inicializarCapa(4,2) #4 caracteristicas, 2 neuronas.

#Salida de capa 1:
y1 = capaNeuronal(w1,x,b1)
#Conectamos la salida de la capa 1 a la capa 2:
y_pred = capaNeuronal(w2,y1,b2)
#Imprimimos la salida:
print(y_pred)

[0.92190169 0.89525204]


Ejemplo 5

In [23]:
# Importa las bibliotecas necesarias
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

# Carga el conjunto de datos Iris
data = load_iris()
X = data.data
y = data.target

# Divide los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Configura y entrena el modelo MLPClassifier
model = MLPClassifier(hidden_layer_sizes=(64, 32), activation='relu', solver='adam', max_iter=1000, random_state=42)
model.fit(X_train, y_train)

# Realiza predicciones en el conjunto de prueba
y_pred = model.predict(X_test)

# Evalúa el modelo utilizando la precisión (accuracy)
accuracy = accuracy_score(y_test, y_pred)
print(f"Precisión del modelo: {accuracy * 100:.2f}%")

Precisión del modelo: 100.00%


In [24]:
import tensorflow as tf
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

# Carga el conjunto de datos Iris
data = load_iris()
X = data.data
y = data.target

# Divide los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Normaliza los datos (opcional pero recomendado)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Define el modelo de la red neuronal utilizando TensorFlow
model = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(X_train.shape[1],)),  # Capa de entrada
    tf.keras.layers.Dense(64, activation='relu'),     # Capa oculta con 64 neuronas y función de activación ReLU
    tf.keras.layers.Dense(32, activation='relu'),     # Capa oculta con 32 neuronas y función de activación ReLU
    tf.keras.layers.Dense(3, activation='softmax')    # Capa de salida con 3 neuronas (clases) y función de activación softmax
])

# Compila el modelo
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Entrena el modelo
model.fit(X_train, y_train, epochs=50, batch_size=32, validation_split=0.2)

# Evalúa el modelo en el conjunto de prueba
y_pred = model.predict(X_test)
y_pred_classes = [tf.argmax(pred).numpy() for pred in y_pred]
accuracy = accuracy_score(y_test, y_pred_classes)
print(f"Precisión del modelo: {accuracy * 100:.2f}%")

Epoch 1/50
3/3 [==============================] - 4s 349ms/step - loss: 1.0221 - accuracy: 0.3542 - val_loss: 1.0011 - val_accuracy: 0.3333
Epoch 2/50
3/3 [==============================] - 0s 78ms/step - loss: 0.9491 - accuracy: 0.6042 - val_loss: 0.9270 - val_accuracy: 0.5000
Epoch 3/50
3/3 [==============================] - 0s 42ms/step - loss: 0.8877 - accuracy: 0.6979 - val_loss: 0.8582 - val_accuracy: 0.9167
Epoch 4/50
3/3 [==============================] - 0s 58ms/step - loss: 0.8297 - accuracy: 0.8229 - val_loss: 0.7976 - val_accuracy: 0.8750
Epoch 5/50
3/3 [==============================] - 0s 51ms/step - loss: 0.7760 - accuracy: 0.7812 - val_loss: 0.7436 - val_accuracy: 0.8750
Epoch 6/50
3/3 [==============================] - 0s 67ms/step - loss: 0.7269 - accuracy: 0.8021 - val_loss: 0.6949 - val_accuracy: 0.8750
Epoch 7/50
3/3 [==============================] - 0s 39ms/step - loss: 0.6796 - accuracy: 0.8021 - val_loss: 0.6524 - val_accuracy: 0.8750
Epoch 8/50
3/3 [==========

In [25]:
import numpy as np

X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([0,1,1,0])


redNeuronal = MLPClassifier(hidden_layer_sizes=(4,2),
                            max_iter=20000,
                            activation ='logistic',
                            tol= 1e-7)

# tol se utiliza para establecer un criterio de tolerancia para la convergencia
# durante el proceso de entrenamiento de la red neuronal. Más específicamente,
# tol controla cuándo se considera que el entrenamiento ha convergido y se
# detiene.

# La notación 1e-7 representa 0.0000001 en notación científica, es decir, un
# número muy pequeño. En este contexto, tol=1e-7 significa que el entrenamiento
# se detendrá cuando la mejora en la función de pérdida sea menor o igual a
#0.0000001 entre dos épocas consecutivas.

redNeuronal.fit(X, Y)
Y_pred = redNeuronal.predict(X)
print(Y_pred)

[0 1 1 0]


Reto 1

In [26]:
import numpy as np

In [27]:
def calcularZ(w, x, b):

SyntaxError: ignored

In [ ]:
w = [1,2,3]
x = [1,2,3]
b = 4
calcularZ(w,x,b)

In [ ]:
def activacion(z):

In [ ]:
activacion(z)

In [ ]:
def neurona(w,x,b):

In [ ]:
w = [1,2,3]
x = [1,2,3]
b = 4
neurona(w,x,b)

Reto 2

In [ ]:
import numpy as np

In [ ]:
def calcularZ(w, x, b):

In [ ]:
w = [1,2,3]
x = [1,2,3]
b = 4
calcularZ(w,x,b)

In [ ]:
def activacionReLU(z):

In [ ]:
activacionReLU(calcularZ(w,x,b))

In [ ]:
def neurona(w,x,b):

In [ ]:
w = [1,2,3]
x = [1,2,3]
b = 4
neurona(w,x,b)